### PR TITLE
Adds the render files interface

### PR DESCRIPTION
**Pull request by umaar**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue: https://github.com/dojo/cli/pull/180
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Adds in the render files interface

### CODE REVIEW

**Comment by umaar** [comment]
@tomdye does this look ok?

**Comment by tomdye** [comment]
Can you add a link to the Pr that adds this functionality to the command helper please?

**Comment by umaar** [comment]
Oh that link is already in the description? Or did you mean another link?

**Comment by tomdye** [comment]
no worries then

**Pull request merged**
